name: grosvenor_prod
version: 1.1.0+787
publish_to: none
description: Grosvenor Casino app

environment:
  sdk: ">=3.1.0 <4.0.0"

dependency_overrides:
  intl: "0.18.1"

dependencies:
  app_tracking_transparency: ^2.0.5
  appsflyer_sdk: ^6.12.2
  auto_animated: ^3.2.0
  auto_route: 7.8.4
  bloc: ^8.1.2
  cached_network_image: ^3.3.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  flutter_flavorizr: ^2.2.1
