name: pipeline
description: A cli to be used alongside production pipelines
version: 0.0.1

executables:
  pipe:

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  args: ^2.4.2
  intl: ^0.19.0

dev_dependencies:
  lints: ^3.0.0
