name: pipeline_cli
description: A cli to be used alongside production pipelines
version: 0.0.1

executables:
  pipe:

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: 3.19.1

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
