---
name: Complete Build Workflow
on:
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'main'

permissions:
  pull-requests: write
  actions: read
  contents: read

jobs: 
  extract:
    name: Gather Info and Send Notification
    runs-on: ubuntu-latest
    # needs: build-apps
    # needs: 
    #   - distribute-apk
    #   - distribute-ipa
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: | 
            ${{ github.event.inputs.branch || github.event.pull_request.head.ref || github.ref_name }}
      
      - name: Generate File and Send Notification
        uses: ./.github/actions/generate-build-info-with-notification
        with:
          PIPELINE_CLI_CONFIG: ${{ secrets.PIPELINE_CLI_CONFIG }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW: PROD_MB

## TESTS
# QA_GC     works
# BETA_GC   works
# PROD_GC   works
# QA_MB     works
# BETA_MB   works
# PROD_MB   works
