---
name: Build
on:
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main
  workflow_dispatch:

jobs: 
  extract:
    name: gather and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract label information
        if: contains(github.event.*.labels.*.name, 'Grosvenor') || contains(github.event.*.labels.*.name, 'grosvenor') 
        id: gc-extract_label_info
        run: |
          label_name="${{ github.event.*.labels.*.name }}"
          label_type=$([[ "${label_name}" == "mecca" || "${label_name}" == "grosvenor" ]] && echo "${label_name}" || echo "unknown")
          echo "Label: ${label_name}"
          echo "Type: ${label_type}"
          echo "label_name=${label_name}" >> $GITHUB_ENV
          echo "label_type=${label_type}" >> $GITHUB_ENV

      - name: Extract label information
        if: contains(github.event.*.labels.*.name, 'Mecca') || contains(github.event.*.labels.*.name, 'mecca')
        id: mb-extract_label_info
        run: |
          label_name="${{ github.event.*.labels.*.name }}"
          label_type=$([[ "${label_name}" == "mecca" || "${label_name}" == "grosvenor" ]] && echo "${label_name}" || echo "unknown")
          echo "Label: ${label_name}"
          echo "Type: ${label_type}"
          echo "label_name=${label_name}" >> $GITHUB_ENV
          echo "label_type=${label_type}" >> $GITHUB_ENV

      - name: Extract last commit hash
        id: extract_commit_hash
        run: |
          last_commit="${{ github.sha }}"
          echo "Last Commit: ${last_commit}"
          echo "last_commit=${last_commit}" >> $GITHUB_ENV
      
      - name: Extract total build time
        id: extract_build_time
        run: |
          build_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          build_info=$(curl -s -H "Accept: application/vnd.github.v3+json" "${build_url}")
          start_time=$(echo "${build_info}" | jq -r '.workflow_run.created_at')
          end_time=$(echo "${build_info}" | jq -r '.workflow_run.updated_at')
          if [ -z "$start_time" ] || [ -z "$end_time" ]; then
            total_build_time=0
          else
            total_build_time=$(($(date -d "${end_time}" +%s) - $(date -d "${start_time}" +%s)))
          fi
          echo "Total Build Time: ${total_build_time} seconds"
          echo "total_build_time=${total_build_time}" >> $GITHUB_ENV

      # - name: Extract pubspec.yaml information
      #   id: extract_pubspec_info
      #   run: |
      #     if [ -f "apps/multichoice/pubspec.yaml" ]; then
      #       pubspec_info=$(cat apps/multichoice/pubspec.yaml | base64)
      #       echo "Pubspec.yaml Information (base64):"
      #       echo "${pubspec_info}" base64 --decode
      #       echo "pubspec_info=${pubspec_info}" >> $GITHUB_ENV
      #     else
      #       echo "pubspec_info=" >> $GITHUB_ENV
      #     fi

      - name: Read pubspec.yaml contents
        id: read-pubspec
        run: |
          PUBSPEC_CONTENTS=$(cat pubspec.yaml)
          echo "PUBSPEC_CONTENTS<<EOF" >> $GITHUB_ENV
          echo "$PUBSPEC_CONTENTS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Extract current date and time
        id: extract_date_time
        run: |
          current_date=$(date -u +"%Y-%m-%d")
          current_time=$(date -u +"%H:%M:%S UTC")
          echo "Current Date: ${current_date}"
          echo "Current Time: ${current_time}"
          echo "current_date=${current_date}" >> $GITHUB_ENV
          echo "current_time=${current_time}" >> $GITHUB_ENV

      - name: Write to build-info.txt
        run: |
          echo "Label: ${label_name}" > build-info.txt
          echo "Type: ${label_type}" >> build-info.txt
          echo "Last Commit: ${last_commit}" >> build-info.txt
          echo "Total Build Time: ${total_build_time} seconds" >> build-info.txt
          echo "Pubspec.yaml Information:" >> build-info.txt
          echo "${PUBSPEC_CONTENTS}" | base64 --decode >> build-info.txt
          echo "Current Date: ${current_date}" >> build-info.txt
          echo "Current Time: ${current_time}" >> build-info.txt

      - name: Upload build-info.txt
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: build-info.txt

      - name: Output artifact ID
        run: |
          echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
          echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
