---
name: Build-android
on:
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs: 
  extract:
    name: gather and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
        # with:
        #   ref: ${{ github.head_ref || github.ref }}
          
      - uses: dart-lang/setup-dart@v1
      - name: Activate Pipeline
        shell: bash
        run: |
          dart pub global activate -s path ./pipeline_cli
          echo -e "Active Packages:\n"
          dart pub global list

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Set up environment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "GitHub token set"

      - name: Extract PR details
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr view --json number --jq '.number')
          LAST_COMMIT=$(gh api repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/commits --jq '.[-1].sha')
          WORKFLOW_NAME=$GITHUB_WORKFLOW
          PR_LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name' | tr '\n' ',' | sed 's/,$//')

          echo "Last Commit: $LAST_COMMIT"
          echo "Workflow Name: $WORKFLOW_NAME"
          echo "PR Labels: $PR_LABELS"

      - name: Extract workflow name
        id: extract-workflow-name
        run: |
          WORKFLOW_NAME=$(basename $GITHUB_WORKFLOW | cut -d'/' -f2)
          echo "WORKFLOW_NAME=$WORKFLOW_NAME" >> $GITHUB_ENV

      - name: Extract Label Information
        if: contains(github.event.pull_request.labels.*.name, 'Grosvenor') || contains(github.event.pull_request.labels.*.name, 'Mecca') 
        id: extract_label_info
        run: |
          label_type="Unknown"
          for label in "${{ toJson(github.event.pull_request.labels.*.name) }}"; do
            if [[ "$label" == *"Grosvenor"* ]]; then
              label_type="Grosvenor"
              break
            elif [[ "$label" == *"Mecca"* ]]; then
              label_type="Mecca"
              break
            fi
          done

          echo "Label: $label_type"
          echo "LABEL_NAME=$label_type" >> $GITHUB_ENV

      - name: Extract last commit hash
        id: extract_commit_hash
        run: |
          last_commit="${{ github.sha }}"
          echo "last_commit=${last_commit}" >> $GITHUB_ENV

      - name: Run custom CLI and capture output
        id: custom-cli
        run: |
          CLI_OUTPUT=$(pipe -g ${WORKFLOW_NAME} -g ${LABEL_NAME} -g ${last_commit})
          echo "CLI_OUTPUT<<EOF" >> $GITHUB_ENV
          echo -e "$CLI_OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Write to output.txt
        run: |
          echo "Current Date: ${current_date}" > output.txt
          echo -e "${CLI_OUTPUT}\n\n" >> output.txt


      - name: Upload output.txt
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: output.txt

      - name: Output artifact ID
        run: |
          echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
          echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
          echo "ARTIFACT_URL=${{ steps.artifact-upload-step.outputs.artifact-url }}" >> $GITHUB_ENV

      - name: Send notification to Slack
        env:
          SLACK_PIPELINE_URL: ${{ secrets.SLACK_PIPELINE_URL }}
          ARTIFACT_URL: ${{ steps.artifact-upload-step.outputs.artifact-url }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
              "artifact_url": "A new production build has finished. You can download a file with all the information here:\n'${ARTIFACT_URL}'",
              "artifact_contents": "" 
              }' $SLACK_PIPELINE_URL

      - name: Send notification to Slack with Artifact Upload
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_PIPELINE_URL }}  # Your Slack webhook URL
          SLACK_CHANNEL: '#your-channel-name'                # Replace with your Slack channel
          SLACK_USERNAME: 'GitHub Actions'                  # Optional: Username for Slack message
          SLACK_COLOR: '#00FF00'                            # Optional: Set a color for the message
          SLACK_ICON_EMOJI: ':rocket:'                      # Optional: Set an emoji icon
          SLACK_TITLE: 'Build Notification'
          SLACK_MESSAGE: |
            A new production build has finished.
            Download the artifact using the link below:
            ${{ steps.artifact-upload-step.outputs.artifact-url }}
        with:
          status: custom
          filename: output.txt                              # Name of the artifact file to upload
          file: output.txt                                  # Path to the file to upload