name: ios-beta-distribution-pipeline 

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'main'
  # pull_request: 
  #   branches: 
  #     - main
jobs:
  deploy:
    name: Deploy to Testflight
    runs-on: macos-13-large
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         ref: ${{github.event.inputs.branch}}
      #################################
      # Flutter Setup
      #################################
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      #################################
      # Get Latest Release Version
      #################################
      - name: Get Latest Release Version
        env:
          APP_PREFIX: gc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          OWNER="Zander-K"
          REPO="pipelines"

          # Fetch latest release information
          latest_release=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$OWNER/$REPO/releases/latest")

          current_version=$(echo "$latest_release" | jq -r '.tag_name')
          version_without_prefix=$(echo "$current_version" | sed -E "s/^${APP_PREFIX}_v_([0-9]+\.[0-9]+\.[0-9]+)\+([0-9]+)$/\1+\2/")
          echo "VERSION_WITHOUT_PREFIX=$version_without_prefix" >> $GITHUB_ENV        
      #################################
      # Rename App
      #################################
      # - name: Rename
      #   run: flutter pub run rename_app:main ios="[BETA] Grosvenor Casino"
      #   working-directory: ./apps/grosvenor_prod 

        
  extract:
    name: Gather Info and Send Notification
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: | 
            ${{ github.event.inputs.branch || github.event.pull_request.head.ref || github.ref_name }}
      
      - name: Generate File and Send Notification
        uses: ./.github/actions/generate-build-info-with-notification
        with:
          PIPELINE_CLI_CONFIG: ${{ secrets.PIPELINE_CLI_CONFIG }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW: BETA_GC