name: mb_android-beta-distribution-workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'main'
  pull_request: 
    branches: 
      - main
jobs:
  build_android:
    name: Build Android app bundle and distribute to beta
    runs-on: macos-13
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         ref: ${{github.event.inputs.branch}}

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter


      #################################
      # Get App Version from pubspec.yaml
      #################################
      - name: Get App Version from pubspec.yaml
        shell: bash
        run: |
          echo "APP_VERSION=$(cat apps/meccabingo_prod/pubspec.yaml | grep -m 1 -o 'version:[^:]*' | cut -f2 -d":" | xargs)" >> $GITHUB_ENV

      #################################
      # Get Latest Release Version
      #################################
      - name: Get Latest Release Version
        shell: bash
        run: |
          build_number=$(echo "$APP_VERSION" | sed 's/.*+//')
          echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV

      #################################
      # Rename App
      #################################
      # - name: Rename
      #   run: flutter pub run rename_app:main android="[BETA] Mecca Bingo"
      #   working-directory: apps/meccabingo_prod 
        


  extract:
    name: Gather Info and Send Notification
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: | 
            ${{ github.event.inputs.branch || github.event.pull_request.head.ref || github.ref_name }}
      
      - name: Generate File and Send Notification
        uses: ./.github/actions/generate-build-info-with-notification
        with:
          PIPELINE_CLI_CONFIG: ${{ secrets.PIPELINE_CLI_CONFIG }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW: BETA_MB