# This Pipeline delivers APK and signed IPA builds to the manual qa team for
# the Mecca Bingo Application.
# It runs when a PR is merged into one of the specified branches and has the label 'Mecca'

name: mb-qa-distribution-pipeline

on:
  # pull_request:
  #   branches: ["develop", "rc-mb"]
  #   types:
  #     - closed
  pull_request: 
    branches: 
      - main
jobs:
  build-apps:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'Mecca')
    runs-on: macos-13
    timeout-minutes: 60
    steps:
      #################################
      # Get App Version from pubspec.yaml
      #################################
      - uses: actions/checkout@v4
      - name: Get App Version from pubspec.yaml
        shell: bash
        run: |
          echo "APP_VERSION=$(cat apps/meccabingo_prod/pubspec.yaml | grep -m 1 -o 'version:[^:]*' | cut -f2 -d":" | xargs)" >> $GITHUB_ENV

      #################################
      # Get Latest Release Version
      #################################
      - name: Get Latest Release Version
        shell: bash
        run: |
          build_name=$(echo "$APP_VERSION" | sed 's/+.*//')
          build_number=$(echo "$APP_VERSION" | sed 's/.*+//')

          echo "BUILD_NAME=$build_name" >> $GITHUB_ENV

          ((build_number++))

          echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV
      
      #################################
      # Update pubspec.yaml With New App version
      #################################
      - name: Update pubspec.yaml with new app version
        uses: ./.github/actions/update-pubspec-version
        with:
          project-path: 'apps/meccabingo_prod'
          build-name: ${{env.BUILD_NAME}}
          build-number: ${{env.BUILD_NUMBER}}


      #################################
      # Setup Flutter
      #################################
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter 



  extract:
    name: Gather Info and Send Notification
    runs-on: ubuntu-latest
    # needs: build-apps
    # needs: 
    #   - distribute-apk
    #   - distribute-ipa
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: | 
            ${{ github.event.inputs.branch || github.event.pull_request.head.ref || github.ref_name }}
      
      - name: Generate File and Send Notification
        uses: ./.github/actions/generate-build-info-with-notification
        with:
          PIPELINE_CLI_CONFIG: ${{ secrets.PIPELINE_CLI_CONFIG }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW: QA_MB